apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: team10
spec:
  selector:
    matchLabels:
      app: java
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: java-api
          image: sireax/java-api:latest
          ports:
            - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: java-api-service
spec:
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001